### PR TITLE
Option to use PR description as merge commit message

### PR DESCRIPTION
**Pull request by zachwhaley**
I've added a checkbox to allow the user to decide if they want to use the PR's description as their merge commit message before merging.

merge-message-option

### CODE REVIEW

**Comment by zachwhaley** [comment]
Hello @yakov116 @bharathwaaj @jerone @billdybas

I was wondering if any of you happened to find an alternative to refined-github's defunct squash-and-merge-message feature?  This is the one thing I valued the most from refined-github yet they don't seem to want to support it :(

Thanks!

P.S. if there is a better means of communicating, please let me know.

**Comment by jerone** [comment]
I never used that feature, but you can ask [here](https://github.com/Mottie/GitHub-userscripts) for an userscript. The author made many very useful userscripts. Maybe he will make another one for you.

**Comment by zachwhaley** [comment]
Thanks @jerone I'll check that out

**Comment by zachwhaley** [comment]
I went ahead and just made my own extension to do this. 

https://github.com/zachwhaley/squashed-merge-message

**Pull request closed without merging**
